#!/bin/bash
#SBATCH -J parse_game_data
#SBATCH -o parse_game_data.out
#SBATCH -e parse_game_data.err
#SBATCH -N 1
#SBATCH -p standard-mem-s
#SBATCH --exclusive
#SBATCH -t "1-0"
#SBATCH --mail-user afish@smu.edu
#SBATCH --mail-type=all

module load gcc-9.2
module load python/3.7.4-3zfxo7j

export PYTHONPATH="${PYTHONPATH}:/hpc/applications/intel/2020/intelpython3/lib/python3.7/site-packages:/users/afish/.local/lib/python3.7/site-packages"

python3 parse_game_data.py 50
